### ISSUE TITLE
Crash when cancelling subscription from AsyncSequencePublisher

### ISSUE THREAD

**Issue by paulz** [josephlord/AsyncSequnceExtensions#5]
Thank you for awesome extensions!

We are trying to use it our app, and see some users repeatedly crash on line 110:

https://github.com/josephlord/AsyncSequnceExtensions/blob/32e1e360c6e2d5a4f54455a47f93bb718e274985/Sources/AsyncSequenceExtensions/AsyncSequencePublisher.swift#L107-L112

`Thread 45: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)`

happens during cancelling subscription

**Comment by josephlord** [comment]
Thanks for the report, I didn't actually know this code was being used in production by anyone. Sounds like a race condition and probably a release after free. Looking at it I think the cancel from within the deinit may be the issue. Try it with the the taskHandle.cancel inline in deinit rather than via the async call in the cancel method (a bigger stack trace might clarify if this is only happening via deinit). If you can't figure out what is wrong it might be worth asking on the Swift Forums.

I'm not currently able to contribute to open source projects (slow permission process at my employer since October) so I can't make a fix but if you were to make one that looked OK I would merge it. It might be that there needs to be an NSLock around some accesses.

I thought that the new official Swift Async Algorithms (https://github.com/apple/swift-async-algorithms) covered this functionality and I was going to recommend switching but I can't actually find Combine interop in there.

**Comment by paulz** [comment]
Thank you for looking into this, @josephlord 

For now we went with another solution: https://www.swiftbysundell.com/articles/creating-combine-compatible-versions-of-async-await-apis/

```
extension PassthroughSubject where Failure == Error {
    static func emittingValues<T: AsyncSequence>(
        from sequence: T
    ) -> Self where T.Element == Output {
        let subject = Self()

        Task {
            do {
                for try await value in sequence {
                    subject.send(value)
                }

                subject.send(completion: .finished)
            } catch {
                subject.send(completion: .failure(error))
            }
        }

        return subject
    }
}
```

It's still cause thread sanitizer warnings in our tests, but somehow does not crash even in a race.
